name: Build Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Create 404.html
        uses: canastro/copy-file-action@0.0.2
        with:
          source: dist/ap-lib/index.html
          target: dist/ap-lib/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: production
          folder: dist/ap-lib
